install:
- source ./support/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- source ./support/compile.sh
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
- echo -n $GIT_TAG > version
- git commit -m "Set build VERSION number" version
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push --quiet https://$GITHUBKEY@github.com/ag-gipp/bib $GIT_TAG > /dev/null
  2>&1
branches:
  except:
  - "/^build-[0-9a-z\\-]*/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YacsSCe5pveUwIPitYbUcPKqU0JnDR82UsxBS0sM/mNIypd4CmdUhkXq2qtZgNKF+t7LI0XespG68QWzDmugF+KSzpVlb3E+F0BGOuV3qb1zECuexgy2mfQ7yTiD7R4+pio9PDY0Nfba70XsT5mXhHtGaQgfIphgfjzsrAdFLGfWa+W7M/uZDzKmCSEXO4ecL1xiNZQGDN3gHXhkHiQSdH3orWP1Vr5nVpdaZyfOrgEhTFCSlSA1IU9Vqj8IBAgeRUDfkAS6buKF6U6mci63SoGnlCFXm4DBLEITXZNc/OtQCKAfVrq3ms3ceHpz1Y3/y+MPdUbXwHFIRjJbPVv2JzEKJRRfZyXtuGer7kh09CrQhxfQL43QRbLPrg8yGqRiZn+N8lf0BXeYNskdd9vKvSOTI1LJ4I/iw3U1RiVcW9dKaHEeycAXxgQFi5HVeLCT0yRJzSw9MIq6PVHhjC3AvDG3aop34/9RzIRlHB6iyLPT6XY5VfVmzfPBfIhMSlAO9Q4Y9V2pa98shKi8knGmQtuQdXmTUL/Daw3/5fMj2SO+KAOOr1QC6vrN3Ia7HA3csZBHq3CVmKLVMzURirDXui94mB5rMSsA4Kb1V9CulRLhcqjPalvXW3u8L0fjbivO9xVVn2iSCJekbxkhOd35ORb3hYmi9XKNbP1Yiuq9KWA=
  file:
  - src/tex/AllRefs.pdf
  - gipp.bib
  on:
    repo: ag-gipp/bib
