install:
- source ./support/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- source ./support/compile.sh
after_success:
- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
branches:
  except:
  - "/^build-[0-9a-z\\-]*/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: V76lRoSbyAH/rVg+gzXeWwAoJJbpGyr8P2uEeVjMoJr+2JvbNT1R3ntnut8vvCBPlVNbWIFkrAiDasTi48xaDKhNhaPhSnRhlSDBoPo2yWXrVESoZmZXhq07kuVRcFBzyNFzDBCbAh7KPJoBQEcIB+ewY8eDL8eAYu0FhQ93zXjKk+9u7Z6QyY/FaTuswVtIwS00wz0pJu/f//k1MzNzb428s5zhtnQzk+g4NiAqaxAB8pveXXm+dsift6yV7gGC/IImqyyZI2pBkkqwX4FVVGhVXqvQB8owhipRPrZnEd6KHCYgmVjO+u08nBpEyDWVk2/eo/iBQ/SA7bXhIefzW7uP7WX1tYkn4L6iEnZXDmAVSfgQt9xuYeZVmJVNNn16BfIondtXA3i+b0c73DJN2qEsLSHGxKK8fdY+Rx6LDFWn7vLtx3jxUW/aQxdtoNoR12EmHNs8ADUau3GB2FnMvMgdEmI7j6VNPB1nJKY0w1nrNOSHDGnYOgqRAt4Khj8RGHySVR+q2nJdTx4CwyQN2BX5LNLzyct/+/c3v5jUrwXY2LxDZGk3PtgbdRky/gM4RYmGoiJ5rXoIEkUFL0Z22EJq5+X8Hsi7tL7uwA2gIEBS+19xTW3zsj8m27fuSyVvBCGyPSDcuORpv2ryZQr8GyESKlTXOIdWJ26A+tUMc8g=
  file:
  - main.pdf
  - gipp.bib
  on:
    repo: ag-gipp/bib
env:
  global:
    secure: eAJppYPl3FzB2+ntMmSLRh45pJpGSSUx/pWLl0sNbGy8bhVLBFMa9DiURVWJ1YKpKDPhjy/7hYn0BmAq8/fDkpp5DMdZu5E0dCk5Ay+AsZR4aikpWyhGJXHc2WEmxbHF/xTV0/9G/jmAhlznRw0CR6E9S5RB0PFOunBlRDmMPSeICL+V5K/2Yc/7Ha/ljZS/gJlSIwZcVHhlaZSLxdi/CRFSx7VgoTIEgzRBYb82y7VbfwpYC0lTknv5Opg82mpbSIb7AgNzGCjLnoHtXntsGQIS8Jcq/oUyNYPT1wocwH/UPNq29/IKQuczEZzxZp/nJq8D4xNmryRd4iNiL7TdA2nqPz7oxdXZTJZRSWP3EZYw5iubYnN8KeoFrRMMFhT91KrRR6wdUq1WoH0bR7I3EwAR/9VuJ1azAFfA1w/wfDeQuuxmHl5kqNerIXRA/gQIpbDNdRz6piic04PFmXTfy5rRCVc6RHj6+sSaZedokkLq2NG7FgOaFGxaYDPWopWKcPoS0L0vArKHjw/moifYW6mDW3zu0DffUeF8sSXtTCbP99tp8hMUmyFPGCTit4MMECu5zTgSraO3E+lle8KxTvw592juCyELXWRsQvXuoMmt8L/mUFpnapHApLA48yBHDBGYW8Cj0xWEacui/utXGFTVyEFY0wKOnuQxELIvXrI=
before_install:
- openssl aes-256-cbc -K $encrypted_125c18bb9738_key -iv $encrypted_125c18bb9738_iv
  -in bibbot.asc.enc -out bibbot.asc -d
